spring:
  application:
    name: api-gateway
  cloud:
      config:
        uri:
          - http://localhost:9000

zuul:
  prefix: /api
  route:
    user-services:
      path: /user-services/**
      service-id: user-services
    task-services:
      path: /task-services/**
      service-id: task-services

server:
  port: 8089

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
      
