spring:
  application:
    name: post-services

  #Datasource
  datasource:
    url: jdbc:mysql://localhost:3306/micro_exp_posts?verifyServerCertificate=false&useSSL=false&requireSSL=false
    username: root
    password: root

  #Jpa Configuration
  jpa:
    generate-ddl: true
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update

# server:
#   port: 8091

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka

ribbon:
  # ReadTimeout: 60000
  # ConnectTimeout: 60000
  https:
    client:
      enabled: true

# hystrix:
#   command:
#     default:
#       execution:
#         isolation:
#           thread:
#             timeoutInMilliseconds: 6000

# feign:
#   httpclient:
#     connection-timeout: 5000
#     max-connections-per-route: 5
#   client:
#     config:
#       default:
#         logger-level: BASIC
#   config:
#     book:
#       connect-timeout: 5000
#       read-timeout: 5000
#       logger-level: FULL
#       decode404: false
#   compression:
#     request:
#       enabled: true
#       min-request-size: 2048
#     response:
#       enabled: true

feign.hystrix.enabled: true
hystrix:
  shareSecurityContext: true
  command:
    default:
      circuitBreaker:
        sleepWindowInMilliseconds: 100000
        forceClosed: true
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 600000

route:
  email: email-service

email-service:
  ribbon:
    DeploymentContextBasedVipAddresses: EMAIL-SERVICES            