spring:
  application:
    name: task-services
  datasource:
    url: jdbc:mysql://localhost:3306/db_tasks?verifyServerCertificate=false&useSSL=false&requireSSL=false
    username: root
    password: root

  jpa:
    generate-ddl: true
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka

#server:
#  port: 8083