spring:
  application:
    name: zuul-server
  cloud:
      config:
        uri:
          - http://localhost:9090

zuul:
  #prefix: /api
  route:
    post-services:
      path: /post-services/**
      service-id: post-services
  ignoredServices: '*'
  host:
    time-to-live: -1
    connect-timeout-millis: 5000
    max-per-route-connections: 10000
    max-total-connections: 5000
    socket-timeout-millis: 60000
  semaphore:
    max-semaphores: 500
    
ribbon:
   ReadTimeout: 60000
   connection-timeout: 3000
   eureka:
      enabled: true

server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
      
