spring:
  application:
    name: zuul-server
  cloud:
      config:
        uri:
          - http://localhost:9090

zuul:
  #prefix: /api
  route:
    post-services:
      path: /post-services/**
      service-id: post-services
    

server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
      
